# Generated by Django 2.2.6 on 2019-11-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
